default_platform(:ios)

platform :ios do
  desc 'Build and upload to TestFlight'
  lane :release do
    sh('echo Building iOS app')
    sh('echo Uploading to TestFlight')
  end
end

platform :android do
  desc 'Build and upload to Play Store'
  lane :release do
    sh('echo Building Android app')
    sh('echo Uploading to Play Store')
  end
end
